[package]
name = "repx-test-utils"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true

