[package]
name = "repx-viz"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
repx-core = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
lazy_static = "1.5"
