[package]
name = "repx-viz"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
repx-core = { path = "../repx-core" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.12"
colored = "3.0"
log = "0.4"
lazy_static = "1.4"
