name: "Nix Build and Test"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fast-checks:
    name: Fast Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run Fast Checks
        run: |
          nix build -L \
            .#checks.x86_64-linux.deadnix \
            .#checks.x86_64-linux.statix \
            .#checks.x86_64-linux.formatting \
            .#checks.x86_64-linux.shebang \
            .#checks.x86_64-linux.shellcheck \
            .#checks.x86_64-linux.machete \
            .#checks.x86_64-linux.clippy

  checks:
    name: Check ${{ matrix.check }}
    needs: fast-checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - repx-py-tests
          - rs-client-tests
          - rs-unit
          - rs-bwrap
          - rs-gc
          - rs-integration
          - rs-containers
          - rs-executor
          - integration
          - invalidation
          - pipeline_logic
          - dynamic_params_validation
          - params
          - params_list
          - e2e-local
          - e2e-remote-local
          - e2e-remote-slurm
          - static-analysis
          - non-nixos-standalone
          - non-nixos-remote
          - fail_missing
          - pass_complex
          - pass_valid
          - e2e-impure
          - e2e-mount-paths
          - e2e-impure-podman
          - e2e-mount-paths-podman
          - e2e-impure-docker
          - e2e-mount-paths-docker
          - incremental-sync
          - large_lab
          - e2e-bwrap-overlay-fallback
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run E2E Check
        run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}

  example-checks:
    name: Example Checks
    needs: fast-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Run Example Checks
        run: nix run -L .#check-repx-examples
